### ISSUE TITLE
小米MIX2S，进入淘宝活动页面之后就没反应了

### ISSUE THREAD

**Issue by caoler** [Dcatfly/auto-task-helper#1]
就进入到领喵币中心点开那个列表之后

**Comment by Dcatfly** [comment]
可否补一张剩余任务数量的截图？
执行任务前应该会有弹窗提示填写执行任务数量，有看到弹窗吗？

**Comment by 541573560** [comment]
我看了一下文档 按理来说setscreenmetrics以后界面坐标分辨率就一样了

**Comment by 541573560** [comment]
我看了一下文档 按理来说setscreenmetrics以后界面坐标分辨率就一样了

**Comment by 541573560** [comment]
我看了一下文档 按理来说setscreenmetrics以后界面坐标分辨率就一样了

**Comment by Dcatfly** [comment]
@541573560 确实如此 但是可能计算的不准确或者所操作的软件并不是所放的，导致可能会出现问题。
已经更新了新的控件选择方法，麻烦重新导入脚本再试一下。

**Comment by Dcatfly** [comment]
@caoler 更新了脚本，可以再试一下看看问题是否依然存在。

**Comment by LANPAST** [comment]
借个issues,华为P10PLUS也是这个问题,能正常进入活动页面,但是进入之后就无操作了

**Comment by Dcatfly** [comment]
@LANPAST  我又更新了脚本，增加了一些日志信息。你再跑一下，然后在脚本菜单里可以拿到最近一次的执行日志，麻烦把日志贴出来我看下。

**Comment by LANPAST** [comment]
> 
> 
> @LANPAST 我又更新了脚本，增加了一些日志信息。你再跑一下，然后在脚本菜单里可以拿到最近一次的执行日志，麻烦把日志贴出来我看下。

你好,我刚刚试了一下,淘宝的现在已经可以正常运行了.
京东的因为我今天已经手动做完了所有任务所以可能试不了

**Comment by Dcatfly** [comment]
@LANPAST  谢谢反馈。明天你再试一下，如果还是没有正常执行麻烦贴一下执行日志。
另外脚本如果没有正确执行并退出，那可能需要手动在Auto.js的管理tab中关闭脚本任务，否则脚本可能会一直阻塞在后台，直到Auto.js被结束进程。

**Comment by LANPAST** [comment]
> 
> 
> @LANPAST 谢谢反馈。明天你再试一下，如果还是没有正常执行麻烦贴一下执行日志。
> 另外脚本如果没有正确执行并退出，那可能需要手动在Auto.js的管理tab中关闭脚本任务，否则脚本可能会一直阻塞在后台，直到Auto.js被结束进程。

我刚刚测试了一下京东的貌似还是不行
![Screenshot_20191027_093515_com jingdong app mall(1)](https://user-images.githubusercontent.com/29109822/67628272-430d2680-f89d-11e9-943a-142793a84435.jpg)
![Screenshot_20191027_093525_org autojs autojs](https://user-images.githubusercontent.com/29109822/67628273-47394400-f89d-11e9-81f2-83e37703c1c6.jpg)

**Comment by Dcatfly** [comment]
> > @LANPAST 谢谢反馈。明天你再试一下，如果还是没有正常执行麻烦贴一下执行日志。
> > 另外脚本如果没有正确执行并退出，那可能需要手动在Auto.js的管理tab中关闭脚本任务，否则脚本可能会一直阻塞在后台，直到Auto.js被结束进程。
> 
> 我刚刚测试了一下京东的脚本就是昨天我说的问题
> ![Screenshot_20191027_093515_com jingdong app mall(1)](https://user-images.githubusercontent.com/29109822/67628272-430d2680-f89d-11e9-943a-142793a84435.jpg)
> ![Screenshot_20191027_093525_org autojs autojs](https://user-images.githubusercontent.com/29109822/67628273-47394400-f89d-11e9-81f2-83e37703c1c6.jpg)

额。。看起来有点神奇，完全没有日志。。。你运行的是最新的脚本？

**Comment by ydali** [comment]
手机为米6，情况与上述类似，从jd首页进入上页面时提示“脚本异常请手动点击进行下一步”日志如下：
![39F57050D63E05FCE62FBA777BFB6978](https://user-images.githubusercontent.com/34053122/67645748-5e436900-f965-11e9-974f-ca7de142f304.png)

**Comment by MyMrXu** [comment]
> 手机为米6，情况与上述类似，从jd首页进入上页面时提示“脚本异常请手动点击进行下一步”日志如下：
> ![39F57050D63E05FCE62FBA777BFB6978](https://user-images.githubusercontent.com/34053122/67645748-5e436900-f965-11e9-974f-ca7de142f304.png)

刚刚我也是这个问题
我手动点击进去了红包页面
然后重开脚本就可以了
好像是第一次红包位置不一样

**Comment by ydali** [comment]
> > 手机为米6，情况与上述类似，从jd首页进入上页面时提示“脚本异常请手动点击进行下一步”日志如下：
> > ![39F57050D63E05FCE62FBA777BFB6978](https://user-images.githubusercontent.com/34053122/67645748-5e436900-f965-11e9-974f-ca7de142f304.png)
> 
> 刚刚我也是这个问题
> 我手动点击进去了红包页面
> 然后重开脚本就可以了
> 好像是第一次红包位置不一样

emmmm   我试了一试  手动点开后重开脚本    然而并没有

**Comment by Dcatfly** [comment]
@ydali 我更新了脚本，你再试一下？
