### ISSUE TITLE
每个浏览任务的时间变长了

### ISSUE THREAD

**Issue by imzhhl** [Dcatfly/auto-task-helper#3]
**描述**
淘宝每个浏览任务的时间变长了，导致没到领金币的时间，就自动退出进行下一个任务了

**复现**
是

**截图**
出现问题时的截图

**环境信息**
小米note5

**日志**
在脚本菜单中可以获得执行日志，请提供最近一次执行的输出日志，这样有助于定位问题。

**其他**

**Comment by Dcatfly** [comment]
@imzhhl 我改了脚本，增加了输入任务时长的功能，你再试下。
