### ISSUE TITLE
请问原项目如何编译。。

### ISSUE THREAD

**Issue by y616468159** [Dcatfly/auto-task-helper#4]
请问大佬原项目如何编译。。

**Comment by Dcatfly** [comment]
@y616468159 
额 我用的Android Studio，挂了代理，自动下载依赖之后编译就过了。
另外我不太懂Android，建议你去原项目的issue中搜索看看。

**Comment by y616468159** [comment]
@Dcatfly 哈哈哈，一样一样，就是为了玩这个活动才来找的，大佬方便加个微信沟通吗。。ID一样

**Comment by y616468159** [comment]
@Dcatfly 大佬你是取的最新代码编译吗，我好像找不到依赖

**Comment by Dcatfly** [comment]
@y616468159  是我fork的版本，也是前几天fork的。微信已加。
