### ISSUE TITLE
今天感觉淘宝有变化

### ISSUE THREAD

**Issue by lsongseven** [Dcatfly/auto-task-helper#5]
**描述**
在执行去浏览任务的时候，一般到第四个任务或者第五个任务的时候，返回的列表将看不到去浏览这个按钮，必须点击其他按钮（比如分享给好友）或者退出到上一页面重新进入才能再次看到去浏览按钮

**复现**
能复现

**截图**
截图不方便，可以及时沟通

**环境信息**
 - 机型  三星s10
 - Version 应该是Android Pie吧。。记不清了

**日志**
在脚本菜单中可以获得执行日志，请提供最近一次执行的输出日志，这样有助于定位问题。

**其他**

**Comment by Dcatfly** [comment]
@lsongseven  好像一直都有这种情况，感觉可能是风控，出现位置不固定，频次不固定。
我更新了代码，做完全部任务之后做一次检查，你试一下，应该会缓解这个问题。
