### ISSUE TITLE
两个脚本都有问题，手机mix2

### ISSUE THREAD

**Issue by someorz** [Dcatfly/auto-task-helper#6]
**描述**
淘宝脚本
WAIT_TIME = WAIT_TIME || dialogs.input("请输入任务等待时长", 23000);
这句去掉，加上const WAIT_TIME = 23000;不然，不能运行
京东脚本
const getRedPacketBtn = desc("全民养红包");
const redPacketBtn = _findOne(getRedPacketBtn, 3000, errorMessageForContinue);
if (redPacketBtn) {
  redPacketBtn.click();
}
这段报错

**复现**
可以复现

**截图**
出现问题时的截图

**环境信息**
 - 机型  小米mix2
 - Version  Android@9

**日志**
在脚本菜单中可以获得执行日志，请提供最近一次执行的输出日志，这样有助于定位问题。

**其他**

**Comment by Dcatfly** [comment]
@someorz 方便给出执行日志吗？
