### ISSUE TITLE
打开领喵币中心后就不动了，这个脚本还有用吗

### ISSUE THREAD

**Issue by moshuchao** [Dcatfly/auto-task-helper#9]
**描述**
清楚的描述问题。

**复现**
关闭原来的脚本任务，重新执行脚本后，是否仍然存在相同问题。

**截图**
出现问题时的截图

**环境信息**
 - 机型  [e.g. 小米8]
 - Version [e.g. Android@7]

**日志**
在脚本菜单中可以获得执行日志，请提供最近一次执行的输出日志，这样有助于定位问题。

**其他**

**Comment by Dcatfly** [comment]
@moshuchao 我试了下在我的机器上还是OK的，正常打开领喵币中心之后应该弹出输入框让输入等待时长，你是这个弹窗没有弹出吗？方便附上日志吗？
